Repository artsy/multienv, pull requests merged in 2021-10, with the labels that each got.

#1 feat: First Release
  .autorc
  .circleci/config.yml
  .github/dependabot.yml
  .gitignore
  .npmignore
  .nvmrc
  package.json
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: canary, Version: Patch

#2 fix: add auto-config
  package.json
  yarn.lock
Labels: canary, Version: Minor

#3 feat: add npm publish config
  package.json
Labels: canary, Version: Minor

#4 chore: CHANGELOG
  CHANGELOG.md
Labels: Version: Patch

#5 feat: Auto (main)
  .autorc
Labels: Version: Patch

#6 feat: Release Script
  package.json
Labels: Version: Patch

#9 feature: Fix Order Bug
  README.md
  src/index.ts
  test/index.test.ts
Labels: Version: Minor
